#import the used companion below from companions folder
from companions.sakura import NAME, TYPE, PERSONA, BEHAVIOUR, SELFIE_TEMPLATE_POST, SELFIE_TEMPLATE_PRE, NSFW_SELFIE_TEMPLATE_POST, NSFW_SELFIE_TEMPLATE_PRE, VOICE_ID, MOOD_KEYWORDS, SEED  #upm package(steamship)

NAME = NAME
TYPE = TYPE
PERSONA = PERSONA
BEHAVIOUR = BEHAVIOUR
SELFIE_TEMPLATE_POST = SELFIE_TEMPLATE_POST
SELFIE_TEMPLATE_PRE = SELFIE_TEMPLATE_PRE
NSFW_SELFIE_TEMPLATE_PRE = NSFW_SELFIE_TEMPLATE_PRE
NSFW_SELFIE_TEMPLATE_POST = NSFW_SELFIE_TEMPLATE_POST
VOICE_ID = VOICE_ID
SEED = SEED

MOOD_KEYWORDS = MOOD_KEYWORDS
