#import the used persona below from personas folder
from companions.lilith import NAME,TYPE,PERSONA,BEHAVIOUR,SELFIE_TEMPLATE_POST,SELFIE_TEMPLATE_PRE,NSFW_SELFIE_TEMPLATE_POST,NSFW_SELFIE_TEMPLATE_PRE,VOICE_ID,MOOD_KEYWORDS #upm package(steamship)

NAME = NAME
TYPE = TYPE
PERSONA = PERSONA
BEHAVIOUR = BEHAVIOUR
SELFIE_TEMPLATE_POST = SELFIE_TEMPLATE_POST
SELFIE_TEMPLATE_PRE = SELFIE_TEMPLATE_PRE
NSFW_SELFIE_TEMPLATE_PRE = NSFW_SELFIE_TEMPLATE_PRE
NSFW_SELFIE_TEMPLATE_POST=NSFW_SELFIE_TEMPLATE_POST
VOICE_ID = VOICE_ID

MOOD_KEYWORDS = MOOD_KEYWORDS